### ISSUE TITLE
Feature Request: UniFi 5.7.20 Stable

### ISSUE THREAD

**Issue by timpur** [linuxserver-archive/docker-unifi-armhf#15]
https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-7-20-Stable-has-been-released/ba-p/2271529

Wondering if this is possible soon? Ill try raise a PR, but dont really know how to do my self yet...

**Comment by tobbenb** [comment]
You didn't read the README well enough. 5.7.20 is available already.

**Comment by timpur** [comment]
That was quick, but its released as unstable, its now a stable version ?

**Comment by tobbenb** [comment]
Not according to us.

**Comment by sparklyballs** [comment]
they might call it stable but it's been nothing but trouble for the team members that have used it and there are multiple threads about issues with it 

hence we marked it unstable

**Comment by timpur** [comment]
okay, i understand :)
